# LinkedListStackDriver: LinkedListStackDriver.o LinkedListStack.o
# 	g++ -g -Wall -std=c++11 -o LinkedListStackDriver LinkedListStackDriver.o LinkedListStack.o
# StackTimesTwoDriver: StackTimesTwoDriver.o StackTimesTwo.o
# 	g++ -g -Wall -std=c++11 -o StackTimesTwoDriver StackTimesTwoDriver.o StackTimesTwo.o
StackPlus100Driver: StackPlus100Driver.o StackPlus100.o
	g++ -g -Wall -std=c++11 -o StackPlus100Driver StackPlus100Driver.o StackPlus100.o

# LinkedListStackDriver.o: LinkedListStackDriver.cpp LinkedListStack.h
# 	g++ -g -Wall -std=c++11 -c LinkedListStackDriver.cpp
# StackTimesTwoDriver.o: StackTimesTwoDriver.cpp StackTimesTwo.h
# 	g++ -g -Wall -std=c++11 -c StackTimesTwoDriver.cpp
StackPlus100Driver.o: StackPlus100Driver.cpp StackPlus100.h
	g++ -g -Wall -std=c++11 -c StackPlus100Driver.cpp

# LinkedListStack.o: LinkedListStack.cpp LinkedListStack.h
# 	g++ -g -Wall -std=c++11 -c LinkedListStack.cpp
# StackTimesTwo.o: StackTimesTwo.cpp StackTimesTwo.h
# 	g++ -g -Wall -std=c++11 -c StackTimesTwo.cpp
StackPlus100.o: StackPlus100.cpp StackPlus100.h
	g++ -g -Wall -std=c++11 -c StackPlus100.cpp