# LinkedListStackDriver: LinkedListStackDriver.o LinkedListStack.o
# 	g++ -g -Wall -std=c++11 -o LinkedListStackDriver LinkedListStackDriver.o LinkedListStack.o
# StackTimesTwoDriver: StackTimesTwoDriver.o StackTimesTwo.o
# 	g++ -g -Wall -std=c++11 -o StackTimesTwoDriver StackTimesTwoDriver.o StackTimesTwo.o
StackPlusDriver: StackPlusDriver.o StackPlus.o
	g++ -g -Wall -std=c++11 -o StackPlusDriver StackPlusDriver.o StackPlus.o

# LinkedListStackDriver.o: LinkedListStackDriver.cpp LinkedListStack.h
# 	g++ -g -Wall -std=c++11 -c LinkedListStackDriver.cpp
# StackTimesTwoDriver.o: StackTimesTwoDriver.cpp StackTimesTwo.h
# 	g++ -g -Wall -std=c++11 -c StackTimesTwoDriver.cpp
StackPlusDriver.o: StackPlusDriver.cpp StackPlus.h
	g++ -g -Wall -std=c++11 -c StackPlusDriver.cpp

# LinkedListStack.o: LinkedListStack.cpp LinkedListStack.h
# 	g++ -g -Wall -std=c++11 -c LinkedListStack.cpp
# StackTimesTwo.o: StackTimesTwo.cpp StackTimesTwo.h
# 	g++ -g -Wall -std=c++11 -c StackTimesTwo.cpp
StackPlus.o: StackPlus.cpp StackPlus.h
	g++ -g -Wall -std=c++11 -c StackPlus.cpp