GraphDriver: GraphDriver.o Graph.o
	g++ -g -Wall -std=c++11 -o GraphDriver GraphDriver.o Graph.o

GraphDriver.o: GraphDriver.cpp Graph.h
	g++ -g -Wall -std=c++11 -c GraphDriver.cpp

Graph.o: Graph.cpp Graph.h
	g++ -g -Wall -std=c++11 -c Graph.cpp