Stackdriver: Stackdriver.o Stack.o
	g++ -g -Wall -std=c++11 -o Stackdriver Stackdriver.o Stack.o

Stackdriver.o: Stackdriver.cpp Stack.h
	g++ -g -Wall -std=c++11 -c Stackdriver.cpp

Stack.o: Stack.cpp Stack.h
	g++ -g -Wall -std=c++11 -c Stack.cpp